language: node_js
sudo: required
before_script:
  - npm install -g polymer-cli web-component-tester
  - polymer install
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then true || polymer test -s
    'default'; fi
dist: trusty
